spring:
  datasource:
    url: ${YANMA408_DB_URL:${SPRING_DATASOURCE_URL}}
    username: ${YANMA408_DB_USERNAME:${SPRING_DATASOURCE_USERNAME}}
    password: ${YANMA408_DB_PASSWORD:${SPRING_DATASOURCE_PASSWORD}}
  h2:
    console:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
